Return-Path: <linux-xfs-owner@vger.kernel.org>
X-Original-To: lists+linux-xfs@lfdr.de
Delivered-To: lists+linux-xfs@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [209.132.180.67])
	by mail.lfdr.de (Postfix) with ESMTP id 4EC44AD0D7
	for <lists+linux-xfs@lfdr.de>; Sun,  8 Sep 2019 23:39:03 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1729928AbfIHVjA (ORCPT <rfc822;lists+linux-xfs@lfdr.de>);
        Sun, 8 Sep 2019 17:39:00 -0400
Received: from mail105.syd.optusnet.com.au ([211.29.132.249]:44166 "EHLO
        mail105.syd.optusnet.com.au" rhost-flags-OK-OK-OK-OK)
        by vger.kernel.org with ESMTP id S1727235AbfIHVjA (ORCPT
        <rfc822;linux-xfs@vger.kernel.org>); Sun, 8 Sep 2019 17:39:00 -0400
Received: from dread.disaster.area (pa49-181-255-194.pa.nsw.optusnet.com.au [49.181.255.194])
        by mail105.syd.optusnet.com.au (Postfix) with ESMTPS id 38CF2361788;
        Mon,  9 Sep 2019 07:38:56 +1000 (AEST)
Received: from dave by dread.disaster.area with local (Exim 4.92)
        (envelope-from <david@fromorbit.com>)
        id 1i74tZ-0004xE-SE; Mon, 09 Sep 2019 07:38:53 +1000
Date:   Mon, 9 Sep 2019 07:38:53 +1000
From:   Dave Chinner <david@fromorbit.com>
To:     kbuild test robot <lkp@intel.com>
Cc:     Christoph Hellwig <hch@lst.de>, kbuild-all@01.org,
        linux-xfs@vger.kernel.org,
        "Darrick J. Wong" <darrick.wong@oracle.com>
Subject: Re: [xfs-linux:iomap-for-next 3/12]
 include/trace/events/iomap.h:49:39: warning: 'struct page' declared inside
 parameter list will not be visible outside of this definition or declaration
Message-ID: <20190908213853.GC16973@dread.disaster.area>
References: <201909072347.PRqg4Chr%lkp@intel.com>
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Disposition: inline
In-Reply-To: <201909072347.PRqg4Chr%lkp@intel.com>
User-Agent: Mutt/1.10.1 (2018-07-13)
X-Optus-CM-Score: 0
X-Optus-CM-Analysis: v=2.2 cv=P6RKvmIu c=1 sm=1 tr=0
        a=YO9NNpcXwc8z/SaoS+iAiA==:117 a=YO9NNpcXwc8z/SaoS+iAiA==:17
        a=jpOVt7BSZ2e4Z31A5e1TngXxSK0=:19 a=kj9zAlcOel0A:10 a=J70Eh1EUuV4A:10
        a=Oh2cFVv5AAAA:8 a=bt8Zh30PAAAA:8 a=QyXUC8HyAAAA:8 a=7-415B0cAAAA:8
        a=pnfwar9_0s6QlxY0SmUA:9 a=CjuIK1q_8ugA:10 a=7KeoIwV6GZqOttXkcoxL:22
        a=biEYGPWJfzWAr4FL6Ov7:22
Sender: linux-xfs-owner@vger.kernel.org
Precedence: bulk
List-ID: <linux-xfs.vger.kernel.org>
X-Mailing-List: linux-xfs@vger.kernel.org

On Sat, Sep 07, 2019 at 11:52:49PM +0800, kbuild test robot wrote:
> tree:   https://kernel.googlesource.com/pub/scm/fs/xfs/xfs-linux.git iomap-for-next
> head:   68494b8e248fe8a7b6e9f88edd9a87661760ddb9
> commit: 4b45a4b5c1f5f52728cec1ce60a3a8f5bb9521b4 [3/12] iomap: add tracing for the address space operations
> config: nds32-allyesconfig (attached as .config)
> compiler: nds32le-linux-gcc (GCC) 8.1.0
> reproduce:
>         wget https://raw.githubusercontent.com/intel/lkp-tests/master/sbin/make.cross -O ~/bin/make.cross
>         chmod +x ~/bin/make.cross
>         git checkout 4b45a4b5c1f5f52728cec1ce60a3a8f5bb9521b4
>         # save the attached .config to linux build tree
>         GCC_VERSION=8.1.0 make.cross ARCH=nds32 
> 
> If you fix the issue, kindly add following tag
> Reported-by: kbuild test robot <lkp@intel.com>
> 
> All warnings (new ones prefixed by >>):
> 
>    In file included from include/trace/events/iomap.h:15,
>                     from <command-line>:
> >> include/trace/events/iomap.h:49:39: warning: 'struct page' declared inside parameter list will not be visible outside of this definition or declaration
>      TP_PROTO(struct inode *inode, struct page *page, unsigned long off, \

The only file that includes trace/events/iomap.h most definitely
has already defined struct page, and


>    include/trace/events/iomap.h:49:18: warning: 'struct inode' declared inside parameter list will not be visible outside of this definition or declaration
>      TP_PROTO(struct inode *inode, struct page *page, unsigned long off, \
>                      ^~~~~

struct inode as well. 

So I'm not sure where the error is actually coming from, nor why it
might only be generated by an obscure architecture (I've never heard
of nds32 until now).

Cheers,

Dave.
-- 
Dave Chinner
david@fromorbit.com
